#!/usr/bin/env python3
"""Regenerate Cursor, Claude Code, and OpenCode config from agent/ source files."""

from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
AGENT = ROOT / "agent"
MANIFEST = AGENT / "manifest.json"
GENERATED_BANNER = "<!-- Generated by agent/sync.py — edit agent/ sources, then re-run sync -->\n\n"


def load_manifest() -> dict[str, Any]:
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


def rule_body(rule_id: str) -> str:
    path = AGENT / "rules" / f"{rule_id}.md"
    if not path.is_file():
        raise FileNotFoundError(f"Missing rule source: {path}")
    return path.read_text(encoding="utf-8").rstrip() + "\n"


def write_cursor_rule(rule: dict[str, Any]) -> None:
    always = rule.get("always", False)
    paths = rule.get("paths") or []
    lines = ["---", f"description: {rule['description']}"]
    if always:
        lines.append("alwaysApply: true")
    if paths:
        lines.append(f"globs: {paths[0]}" if len(paths) == 1 else f"globs: {json.dumps(paths)}")
    lines.extend(["---", ""])
    out = ROOT / ".cursor" / "rules" / f"{rule['id']}.mdc"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + rule_body(rule["id"]), encoding="utf-8")


def write_claude_rule(rule: dict[str, Any]) -> None:
    paths = rule.get("paths") or []
    prefix = ""
    if paths:
        path_lines = "\n".join(f'  - "{p}"' for p in paths)
        prefix = f"---\npaths:\n{path_lines}\n---\n\n"
    out = ROOT / ".claude" / "rules" / f"{rule['id']}.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(prefix + rule_body(rule["id"]), encoding="utf-8")


def sync_agents_md() -> None:
    src = AGENT / "AGENTS.md"
    if not src.is_file():
        raise FileNotFoundError(f"Missing {src}")
    content = src.read_text(encoding="utf-8")
    (ROOT / "AGENTS.md").write_text(GENERATED_BANNER + content, encoding="utf-8")


def write_claude_md() -> None:
    body = """@AGENTS.md

## Claude Code

Path-scoped rules load from `.claude/rules/` (generated from `agent/rules/`).
Project skills symlink to `agent/skills/`. Regenerate with `python3 agent/sync.py`.
"""
    (ROOT / "CLAUDE.md").write_text(GENERATED_BANNER + body, encoding="utf-8")


def write_opencode_json(manifest: dict[str, Any]) -> None:
    instructions = ["AGENTS.md"]
    instructions.extend(f"agent/rules/{rule['id']}.md" for rule in manifest["rules"])
    config = {"instructions": instructions}
    (ROOT / "opencode.json").write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")


def sync_skill(skill_id: str) -> None:
    src = (AGENT / "skills" / skill_id).resolve()
    if not src.is_dir():
        raise FileNotFoundError(f"Missing skill source: {src}")
    link_target = Path("../../agent/skills") / skill_id
    for tool_dir in ("cursor", "claude"):
        dest = ROOT / f".{tool_dir}" / "skills" / skill_id
        dest.parent.mkdir(parents=True, exist_ok=True)
        if dest.is_symlink():
            dest.unlink()
        elif dest.exists():
            if dest.is_dir():
                shutil.rmtree(dest)
            else:
                dest.unlink()
        dest.symlink_to(link_target)


def sync_all() -> None:
    manifest = load_manifest()
    sync_agents_md()
    for rule in manifest["rules"]:
        write_cursor_rule(rule)
        write_claude_rule(rule)
    write_claude_md()
    write_opencode_json(manifest)
    for skill_id in manifest.get("skills", []):
        sync_skill(skill_id)


def main() -> int:
    try:
        sync_all()
    except (FileNotFoundError, KeyError, json.JSONDecodeError) as exc:
        print(f"sync failed: {exc}", file=sys.stderr)
        return 1
    print("Synced agent config → Cursor (.cursor/), Claude Code (.claude/, CLAUDE.md), OpenCode (opencode.json, AGENTS.md)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
